CFLAGS += -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fno-stack-protector -I$(IHKBASE)/x86_common/include -mcmodel=kernel
IHK_OBJS += setup.o cpu.o interrupt.o memory.o trampoline.o local.o context.o
IHK_OBJS += dma.o perfctr.o
IHK_SRCDIRS += x86_common
