# Makefile.config COPYRIGHT FUJITSU LIMITED 2015-2016
include $(IHKBASE)/$(TARGETDIR)/Makefile.predefines

CFLAGS += $(foreach i, $(shell seq 1 100), $(addprefix -DPOSTK_DEBUG_ARCH_DEP_, $(i)))
CFLAGS += $(foreach i, $(shell seq 1 100), $(addprefix -DPOSTK_DEBUG_TEMP_FIX_, $(i)))
CFLAGS += -mgeneral-regs-only

IHK_SRCDIRS += $(SRC)/../arch/$(IHKARCH)/kernel
IHKARCH = arm64

IHK_OBJS += setup.o
IHK_OBJS += dma.o
include $(SRC)/../arch/$(IHKARCH)/kernel/Makefile.arch
