CFLAGS += -Wall -O -Iinclude -I../generic/include -Wno-unused-function
OBJS += string.o vsprintf.o abort.o
AALBASE = ..
AAL = [AAL]

include ../Makefile.common

aal.o: $(OBJS)
	$(ld_cmd)

%.o: %.c
	$(cc_cmd)

%.o: ../generic/%.c
	$(cc_cmd)

clean:
	$(RM) *.o
