CFLAGS += -DATTACHED_MIC -DKNC_MAP_MICPA
CFLAGS += -I$(IHKBASE)/../linux/driver/attached/mic/include
CFLAGS += -I$(IHKBASE)/../include
CFLAGS += -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fno-stack-protector
CFLAGS += -mcmodel=kernel -mno-red-zone

LDFLAGS += -m elf_k1om

IHK_SRCDIRS += $(SRC)/../arch/$(IHKARCH)/kernel
IHKARCH = x86

IHK_OBJS += sfi.o
IHK_OBJS += setup.o
IHK_OBJS += dma.o
include $(SRC)/../arch/$(IHKARCH)/kernel/Makefile.arch
