CFLAGS += -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fno-stack-protector -mcmodel=kernel
IHKARCH = x86
CFLAGS += -DKNC_MAP_MICPA -DATTACHED_MIC -I$(IHKBASE)/../linux/driver/attached/mic/include -I$(IHKBASE)/../include
LDFLAGS += -m elf_k1om
IHK_SRCDIRS += $(SRC)/../arch/$(IHKARCH)/kernel
IHK_OBJS += setup.o cpu.o sfi.o interrupt.o memory.o trampoline.o local.o context.o dma.o perfctr.o

