CFLAGS += -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fno-stack-protector -I$(AALBASE)/x86_common/include
LDFLAGS += -m elf_l1om
AAL_SRCDIRS += x86_common
AAL_OBJS += setup.o cpu.o sfi.o interrupt.o memory.o
