CFLAGS += -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fno-stack-protector -mcmodel=kernel -DBUILTIN_MIC
IHK_OBJS += setup.o cpu.o interrupt.o memory.o trampoline.o local.o context.o
IHK_OBJS += dma.o perfctr.o syscall.o
IHKARCH = x86
IHK_SRCDIRS += $(SRC)/../arch/$(IHKARCH)/kernel
