CFLAGS += -DBUILTIN_MIC
CFLAGS += -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fno-stack-protector
CFLAGS += -mcmodel=kernel -mno-red-zone

IHK_SRCDIRS += $(SRC)/../arch/$(IHKARCH)/kernel
IHKARCH = x86

IHK_OBJS += setup.o cpu.o interrupt.o memory.o trampoline.o local.o context.o
IHK_OBJS += dma.o perfctr.o syscall.o vsyscall.o
