CFLAGS += -DBUILTIN_X86
CFLAGS += -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fno-stack-protector
CFLAGS += -mcmodel=kernel -mno-red-zone

ifeq ($(ARCH), arm64)
CFLAGS += $(foreach i, $(shell seq 6 106), $(addprefix -DPOSTK_DEBUG_ARCH_DEP_, $(i)))
CFLAGS += $(foreach i, $(shell seq 1 100), $(addprefix -DPOSTK_DEBUG_TEMP_FIX_, $(i)))
endif

IHK_SRCDIRS += $(SRC)/../arch/$(IHKARCH)/kernel
IHKARCH = x86

IHK_OBJS += setup.o
IHK_OBJS += dma.o
include $(SRC)/../arch/$(IHKARCH)/kernel/Makefile.arch
