CFLAGS += -DBUILTIN_X86
CFLAGS += -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fno-stack-protector
CFLAGS += -mcmodel=kernel -mno-red-zone

IHK_SRCDIRS += $(SRC)/../arch/$(IHKARCH)/kernel
IHKARCH = x86

IHK_OBJS += setup.o
IHK_OBJS += dma.o
include $(SRC)/../arch/$(IHKARCH)/kernel/Makefile.arch
